M48
; DRILL file {KiCad 7.0.0} date Tue 28 Feb 2023 11:46:05 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-28T23:46:05-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X127.67Y-76.85
X132.75Y-128.92
X160.69Y-128.92
X175.93Y-78.12
T0
M30
